# -*- coding: utf-8 -*-
"""Week2python(Overview).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Px-dBBO-wOQ8WN7bYxzHSrDvU-U1TTGe
"""

a = 10

a

## this is a function
## for single we use ##
## Comments
# this is a comment
a = 20
a



"""# Ishan
## Ishan
### Ishan
"""

"""
Example of multiline comment
hello this a example of python
ashDEdfL
jhrfl
"""
a = 20
a

"""## Numbers"""

1 + 3

print(1+3)

a=5
a

print(a)

print("Hello Ishan \nI work in Tesla")

"""# Variables Assignment"""

name = "Ishan"
company = "Tesla and Google"

name = "Bala"

company

number = 10

number

name

number = 20

number

type("")

type(number)

Decimal_num = 2.5

Decimal_num

type(Decimal_num)

type("hello")

1 + 2j

type(1+2j)

print('hello')

print("hello")

"""####bad way
#### dont start the variable name wkith numbers
1a
3answer

"""

number1 = 23

## Variables are case sensitive
company = "ineuron"
Company = "PWSKILLS"
print(company)
print(Company)

"""## Reserved keywords
'''
int, float, len, complex, bool, str, return, yield
'''
"""

#float =32 (Don't Do)

##Boolean
True

False

True and False

True or False

not True

type(not False)

## Typecasting
bool(0)

str(23)

int('23')

type(int('23'))

bool(1)

a = 1
if type(bool(a))==True:
  print("True")

type(bool(a))==True

bool(a)

type(bool(a))

a = 1
if bool(a)==True:
  print("True")

int('1234')

"""### Dynamic Typing"""

a = 12
str1 = "Ishan"
a = "var"

print(type(a))

int(1.54)

## concatenation between different types

"1" +"1"

int("1" +"1")

int("1") + int("1")

"1" * 100

"123"

int("123")

float(123)

#int("acd")

"1" * int("1")

type(a)

bool(2)

bool(-1) #unless 0

#type = bool(-2) reserved keyword

