# -*- coding: utf-8 -*-
"""Week2python(Basics).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu_-VOFRCKnO7_Pm_ddmBHaq-GffiKL-
"""

a = 10

a = "c"

type(a)

int()

int('123')

#int('abcd')

print("Hello World")

print("123")

print(123)

age = 22
print("My age is :",age)

print("My age is : {age}")

## f string
print(f"My age is : {age}")

## format()
name = "Ishan"
age = 22
print("My name is {} and age is {}".format(name,age))

print("My name is {} and age is {}".format(age,name))

#placeholder
print("My name is {firstname} and age is {firstage}".format(firstname=name,firstage=age))

name = "Ishan"
age = 22
degree = "BSC"
" My age is 22 and i have completed : my degree of Bsc with the name of Ishan Sharma"
print("My age is {} and i have completed: my degree of {} with the name of {}".format(age,degree,name))

print(f"My age is {age} and i have completed: my degree of {degree} with the name of {name}")

## Control Flow
### Decision Making statements

## If Statements
age = 18
if age  >= 18:
  print("You are eligible to vote")

## If Statements
age = 18
if age  < 18:
  print("You are not  eligible to vote")

## If Statements
age = 17
if age  < 18:
  print("You are not  eligible to vote")

17 < 18

input()

name = input("Enter the name")

name

age = int(input("Enter your age "))

type(age)

## Task
## Take a input of age
## Check whether age >=18 and age<=32
## display a message you are young blood

True and False

age = int(input("Enter the age "))
if age>=18 and age <= 32:
  print("You are young blood")

22>=18 and 22 <= 45

age = int(input("Enter the age "))
if age>=18 and age <= 45:
  print("You are young blood")

## if else statements
age = int(input("Enter the age "))
if age>=18 and age <= 45:
  print("You are young blood")
else:
  print("Thank you we will let you know")

## mall - input the product price
## product >1000rs 20% off
## print the product price after removing the discount
## product <=1000rs 30%off
## print the product price after removing the discount

product_price = int(input("Enter the price"))
if product_price > 1000:
  print("The price of the product is {}".format(product_price*0.8))
else:
  print("The price of the product is {}".format(product_price*0.7))

product_price = int(input("Enter the price"))
if product_price > 1000:
  print("The price of the product is {}".format(product_price*0.8))
else:
  print("The price of the product is {}".format(product_price*0.7))

product_price = int(input("Enter the price"))
if product_price > 1000:
  print(f"The price of the product is {product_price*0.8}")
else:
  print("The price of the product is {}".format(product_price*0.7))

## mall - input the product price
## product > 3000rs 20% off
## print the product price after removing the discount
## product >= 2000rs and <=3000 30%off
## print the product price after removing the discount
##product <= 1000 rs and <= 2000rs 40% off
## print the product price fter removing the discount

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_prize*0.7))
else:
  print("The price of the product is {}".format(product_price*0.6))

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("The price of the product is {}".format(product_price*0.6))

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("The price of the product is {}".format(product_price*0.6))

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("The price of the product is {}".format(product_price*0.6))

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("The price of the product is {}".format(product_price*0.6))

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("let's drink tea")

## mall - input the product price
## product > 3000rs 20% off
## print the product price after removing the discount
## product >= 2000rs and <=3000 30%off
## print the product price after removing the discount
##price == 2999 u will get additional gift
##product <= 1000 rs and <= 2000rs 40% off
## print the product price fter removing the discount

product_price = int(input("Enter the price"))
if product_price > 3000:
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  if product_price==2999:      #nested if
    print("Congratulations you get an additional gift")
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("let's drink tea")

## mall - input the product price
## product > 3000rs 20% off
## price == 4000 u will get a Goa trip
## print the product price after removing the discount
## product >= 2000rs and <=3000 30%off
## print the product price after removing the discount
##price == 2999 u will get additional gift
##product <= 1000 rs and <= 2000rs 40% off
## print the product price fter removing the discount

product_price = int(input("Enter the price"))
if product_price > 3000:
  if product_price == 4000:
    print("you will get a trip to Goa")
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  if product_price==2999:      #nested if
    print("Congratulations you get an additional gift")
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("let's drink tea")

product_price = int(input("Enter the price"))
if product_price > 3000:
  if product_price == 4000:
    print("you will get a trip to Goa")
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  if product_price==2999:      #nested if
    print("Congratulations you get an additional gift")
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("let's drink tea")
  print("I will also be there")

#comparison operator
True==True

product_price = int(input("Enter the price"))
if product_price > 3000:
  if product_price == 4000:
    print("you will get a trip to Goa")
  print(f"The price of the product is {product_price*0.8}")
elif product_price >= 2000 and product_price <= 3000:
  if product_price==2999:      #nested if
    print("Congratulations you get an additional gift")
  print("The price of the product is {}".format(product_price*0.7))
elif product_price >= 100 and product_price <= 2000:
  print("The price of the product is {}".format(product_price*0.7))
else:
  print("let's drink tea")
  print("I will also be there")

## Single statement suites
val = int(input('Enter the number'))
if (val <= 999):print("Value is less than equal to 999")
else:
  print("Go Home")

"""## Loops statements
1. while loop
2. for loop
3. nested loops
4. Loop control (break,continue, pass)
"""

# while loop
joining_age = 25
while joining_age <= 60:
  joining_age = joining_age + 1
  print(joining_age)

# while loop while_else
joining_age = 25
while joining_age <= 60:
  joining_age = joining_age + 1
  print(joining_age)
else:
  print("Its time to retirement")

## ATM machine with 1000rs
total_amount = 1000
while total_amount !=0:
  total_amount = total_amount-100
  print(total_amount)

## ATM machine with 1000rs
total_amount = 1000
while total_amount !=0:
 print(total_amount)
 total_amount = total_amount-100

## ATM machine with 1000rs
total_amount = 1000
while total_amount !=0:
 print(total_amount)
 total_amount = total_amount-100
else:
  print("Put more money bank people")

"""# For Loop"""

lst = ["Krish", 1, 2, 3, 4, "apple", "banana"]

type(lst)

lst[0]

lst[4]

for x in lst:
  print(x)

fruits_list = ["Mango", "Cherry", "Apple", "Papaya", "Banana"]

for a in fruits_list:
  print(a)

for a in fruits_list:
  print(a)
  if a=="Cherry":
    print("The fruit is cherry")

#same line
for a in fruits_list:
  print(a,end="")
  if a=="Cherry":
    print("The fruit is cherry")

for a in fruits_list:
  print(a,end="")
  if a=="Cherry":
    print("The fruit is cherry")
    break

fruits = 'mango'
for x in fruits:
  print(x)

fruits[1]

fruits = 'mango'
for x in fruits:
  print(x,end='')

range(1,6)

for i in range(1,6):
  print(i)

for i in range(1,10,2):
  print(i)

### Nested Loops
n = 7

for i in range(0,n):
  for j in range(0,i+1):
    print("*")

### Nested Loops
n = 7

for i in range(0,n):
  for j in range(0,i+1):
    print("*",end="")

n = 7

for i in range(0,n):
  for j in range(0,i+1):
    print("*",end="")
  print("\r")

## Loop controls
## Break and Continue
fruits_list = ["Mango","Cherry", "Apple", "Papaya", "Banana"]

for i in fruits_list:
  if i=='Apple':
    print("The fruit is apple")
    break
  print(i)

for i in fruits_list:
  if i=='Apple':
    print("The fruit is apple")
    break
  print(i)

for i in fruits_list:
  if i=='Apple':
    print("The fruit is apple")
    continue
  print(i)

i = 10
i < 12 and i > 9

i = 10
if (i < 12 and i > 9):
  print("Condition is true")

